notifications:
 email:
  recipients:
    - etienne.thevenot@cea.fr

before_install:
 - sudo apt-get install -y python-virtualenv
 - sudo apt-get install -y ant
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install --upgrade pip setuptools
 - pip install planemo
 - planemo conda_init
 - planemo conda_install univariate_config.xml

script:
 - ant test
